
# Prometheus Monitor Service (Metrics)
apiVersion: operator.acceldata.io/v1beta1
kind: VMServiceScrape
metadata:
  labels:
    control-plane: controller-manager
  name: controller-manager-metrics-monitor
  namespace: system
spec:
  endpoints:
    - path: /metrics
      port: https
  selector:
    matchLabels:
      control-plane: controller-manager
