apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vm-operator-manager-role
rules:
- apiGroups:
    - ""
  resources:
    - configmaps
    - configmaps/finalizers
  verbs:
    - '*'
- apiGroups:
    - ""
  resources:
    - endpoints
  verbs:
    - '*'
- apiGroups:
    - ""
  resources:
    - events
  verbs:
    - '*'
- apiGroups:
    - ""
  resources:
    - namespaces
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - ""
  resources:
    - persistentvolumeclaims
    - persistentvolumeclaims/finalizers
  verbs:
    - '*'
- apiGroups:
    - ""
  resources:
    - pods
  verbs:
    - '*'
- apiGroups:
    - ""
  resources:
    - secrets
    - secrets/finalizers
  verbs:
    - '*'
- apiGroups:
    - ""
  resources:
    - services
    - services/finalizers
  verbs:
    - '*'
- apiGroups:
    - apps
  resources:
    - deployments
    - deployments/finalizers
  verbs:
    - '*'
- apiGroups:
    - apps
  resources:
    - replicasets
  verbs:
    - '*'
- apiGroups:
    - apps
  resources:
    - statefulsets
    - statefulsets/finalizers
    - statefulsets/status
  verbs:
    - '*'
- apiGroups:
    - policy
  resources:
    - poddisruptionbudgets
    - poddisruptionbudgets/finalizers
  verbs:
    - '*'
- apiGroups:
    - monitoring.coreos.com
  resources:
    - '*'
  verbs:
    - '*'
- apiGroups:
    - operator.acceldata.io
  resources:
    - vmagents
    - vmagents/finalizers
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - operator.acceldata.io
  resources:
    - vmagents/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - operator.acceldata.io
  resources:
    - vmalertmanagers
    - vmalertmanagers/finalizers
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - operator.acceldata.io
  resources:
    - vmalertmanagers/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - operator.acceldata.io
  resources:
    - vmalerts
    - vmalerts/finalizers
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - operator.acceldata.io
  resources:
    - vmalerts/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - operator.acceldata.io
  resources:
    - vmclusters
    - vmclusters/finalizers
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - operator.acceldata.io
  resources:
    - vmclusters/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - operator.acceldata.io
  resources:
    - vmpodscrapes
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - operator.acceldata.io
  resources:
    - vmpodscrapes/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - operator.acceldata.io
  resources:
    - vmrules
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - operator.acceldata.io
  resources:
    - vmrules/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - operator.acceldata.io
  resources:
    - vmservicescrapes
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - operator.acceldata.io
  resources:
    - vmservicescrapes/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - operator.acceldata.io
  resources:
    - vmprobes
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - operator.acceldata.io
  resources:
    - vmprobes/status
  verbs:
    - get
    - patch
    - update

- apiGroups:
    - operator.acceldata.io
  resources:
    - vmsingles
    - vmsingles/finalizers
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - operator.acceldata.io
  resources:
    - vmsingles/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - "discovery.k8s.io"
  resources:
    - endpointslices
  verbs:
    - 'list'
    - 'watch'
    - 'get'
- apiGroups:
    - ""
  resources:
    - nodes
    - nodes/proxy
    - nodes/metrics
    - services
    - endpoints
    - pods
    - configmaps
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - extensions
    - "extensions"
    - networking.k8s.io
    - "networking.k8s.io"
  resources:
    - ingresses
  verbs:
    - get
    - list
    - watch
    - delete
- nonResourceURLs:
    - "/metrics"
    - "/metrics/resources"
  verbs:
    - get
    - watch
    - list
- apiGroups:
    - "rbac.authorization.k8s.io"
  resources:
    - clusterrolebindings
    - clusterrolebindings/finalizers
    - clusterroles
    - clusterroles/finalizers
    - roles
    - rolebindings
  verbs:
    - get
    - list
    - create
    - patch
    - update
    - watch
    - delete
- apiGroups:
    - "policy"
  resources:
    - podsecuritypolicies
    - podsecuritypolicies/finalizers
  verbs:
    - get
    - list
    - create
    - patch
    - update
    - use
    - watch
    - delete
- apiGroups:
    - ""
  resources:
    - serviceaccounts
    - serviceaccounts/finalizers
  verbs:
    - get
    - list
    - create
    - watch
    - delete
    - patch
    - update
- apiGroups:
    - operator.acceldata.io
  resources:
    - vmnodescrapes
    - vmnodescrapes/finalizers
  verbs:
    - '*'
- apiGroups:
    - operator.acceldata.io
  resources:
    - vmnodescrapes/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - operator.acceldata.io
  resources:
    - vmstaticscrapes
    - vmnodescrapes/finalizers
  verbs:
    - '*'
- apiGroups:
    - operator.acceldata.io
  resources:
    - vmstaticscrapes/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - storage.k8s.io
  resources:
    - storageclasses
  verbs:
    - list
    - get
    - watch
- apiGroups:
    - route.openshift.io
    - image.openshift.io
  resources:
    - routers/metrics
    - registry/metrics
  verbs:
    - get
- apiGroups:
    - autoscaling
  resources:
    - horizontalpodautoscalers
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - operator.acceldata.io
  resources:
    - vmusers
    - vmusers/finalizers
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - operator.acceldata.io
  resources:
    - vmusers/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - operator.acceldata.io
  resources:
    - vmauths
    - vmauths/finalizers
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - operator.acceldata.io
  resources:
    - vmauths/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - networking.k8s.io
    - extensions
  resources:
    - ingresses
    - ingresses/finalizers
  verbs:
    - create
    - delete
    - get
    - patch
    - update
    - watch
- apiGroups:
    - apiextensions.k8s.io
  resources:
    - customresourcedefinitions
  verbs:
    - get
    - list
- apiGroups:
  - operator.acceldata.io
  resources:
  - vmalertmanagerconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.acceldata.io
  resources:
  - vmalertmanagerconfigs/status
  verbs:
  - get
  - patch
  - update
