# permissions for end users to edit vmagents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmagent-editor-role
rules:
- apiGroups:
  - operator.acceldata.io
  resources:
  - vmagents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  - deletecollection
- apiGroups:
  - operator.acceldata.io
  resources:
  - vmagents/status
  verbs:
  - get
