# permissions for end users to view vmagents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmagent-viewer-role
rules:
- apiGroups:
  - operator.acceldata.io
  resources:
  - vmagents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.acceldata.io
  resources:
  - vmagents/status
  verbs:
  - get
