# permissions for end users to view vmalertmanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmalertmanager-viewer-role
rules:
- apiGroups:
  - operator.acceldata.io
  resources:
  - vmalertmanagers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.acceldata.io
  resources:
  - vmalertmanagers/status
  verbs:
  - get
