# permissions for end users to edit vmalertmanagerconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmalertmanagerconfig-editor-role
rules:
- apiGroups:
  - operator.acceldata.io
  resources:
  - vmalertmanagerconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.acceldata.io
  resources:
  - vmalertmanagerconfigs/status
  verbs:
  - get
