# permissions for end users to view vmalertmanagerconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmalertmanagerconfig-viewer-role
rules:
- apiGroups:
  - operator.acceldata.io
  resources:
  - vmalertmanagerconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.acceldata.io
  resources:
  - vmalertmanagerconfigs/status
  verbs:
  - get
