# permissions for end users to edit vmalertmanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmalertmanager-editor-role
rules:
- apiGroups:
  - operator.acceldata.io
  resources:
  - vmalertmanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  - deletecollection
- apiGroups:
  - operator.acceldata.io
  resources:
  - vmalertmanagers/status
  verbs:
  - get
