# permissions for end users to edit vmnodescrapes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmnodescrape-editor-role
rules:
- apiGroups:
  - operator.acceldata.io
  resources:
  - vmnodescrapes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  - deletecollection
- apiGroups:
  - operator.acceldata.io
  resources:
  - vmnodescrapes/status
  verbs:
  - get
