# permissions for end users to edit vmpodscrapes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmpodscrape-editor-role
rules:
- apiGroups:
  - operator.acceldata.io
  resources:
  - vmpodscrapes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  - deletecollection
- apiGroups:
  - operator.acceldata.io
  resources:
  - vmpodscrapes/status
  verbs:
  - get
