# permissions for end users to view vmprobes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmprobe-viewer-role
rules:
- apiGroups:
  - operator.acceldata.io
  resources:
  - vmprobes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.acceldata.io
  resources:
  - vmprobes/status
  verbs:
  - get
