# permissions for end users to view vmrules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmrule-viewer-role
rules:
- apiGroups:
  - operator.acceldata.io
  resources:
  - vmrules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.acceldata.io
  resources:
  - vmrules/status
  verbs:
  - get
