# permissions for end users to view vmservicescrapes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmservicescrape-viewer-role
rules:
- apiGroups:
  - operator.acceldata.io
  resources:
  - vmservicescrapes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.acceldata.io
  resources:
  - vmservicescrapes/status
  verbs:
  - get
