# permissions for end users to view vmstaticscrapes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmstaticscrape-viewer-role
rules:
- apiGroups:
  - operator.acceldata.io
  resources:
  - vmstaticscrapes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.acceldata.io
  resources:
  - vmstaticscrapes/status
  verbs:
  - get
