apiVersion: operator.acceldata.io/v1beta1
kind: VMServiceScrape
metadata:
  name: example-scrape
spec:
  endpoints:
    - port: http
  namespaceSelector: {}
  selector:
    matchLabels:
      app.kubernetes.io/name: example-application
      monitored-by: vm-operator
